name: siamese_regression
channels:
  - rdkit
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.3
  - pandas=1.3.5
  - python=3.7.4
  - pip
  - rdkit=2020.09.1.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tqdm=4.62.3
  - seaborn
  - matplotlib
  - yaml
  - pip:
    - levenshtein==0.18.1
    - markdown==3.3.6
    - more-itertools==8.12.0
    - optuna==2.3.0
    - pytorch-lightning==1.2.3

